# © 2022 ~ 2023 邱泽帆


services:
  
  letsencrypt_nginx:
    container_name: nginx
    image: nginx:1.29.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./letsencrypt/nginx/etc/templates:/etc/nginx/templates:ro
      - ../data/letsencrypt/etc/letsencrypt:/etc/letsencrypt:ro
      - ../data/letsencrypt/webroot:/webroot:ro
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "7"
  letsencrypt_renew:
    container_name: letsencrypt_renew
    image: certbot/certbot:v5.1.0
    command: renew --agree-tos -n --cert-name freefont.showtimemaker.com --webroot-path /webroot --force-renewal
    volumes:
      - ../data/letsencrypt/etc/letsencrypt:/etc/letsencrypt
      - ../data/letsencrypt/webroot:/webroot